name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-24.04
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Stale
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been marked stale because it has been open for 60 days with no activity.'
          stale-pr-message: 'This pull request has been marked stale because it has been open for 60 days with no activity.'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
