name: Publish to Winget

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04

    steps:
      - name: Publish to Winget
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: schollz.croc
          installers-regex: '_Windows-\w+\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}
